---
title: "P8451_HW7_ML"
author: "Ruixi Li"
date: "2024-02-28"
output: html_document
---

```{r libraries}
library(tidyverse)
library(dplyr)
library(caret)

```

# Data preparation

```{r load data, message=FALSE, warning=FALSE}
# load the data, remove dupplicate and clean variable names
mi = read_csv("mi.data.csv") |> distinct() |> janitor::clean_names()

#mi |> group_by(fc) |> count()

skimr::skim(mi)# all variables are numeric

# In machine learning, we don't need to recode the character variables into its 'label', instead we convert them as factor with set reference.
cate_var = c("sex","pulm_adema","fc","arr","diab","obesity","asthma","readmission")
# convert all categorical variables into factors
mi = mi |> mutate(across(all_of(cate_var),as.factor))

# set all categorical variables' reference group as '0'
mi = mi |> mutate(across(all_of(cate_var), ~relevel(.x, ref = "0")))

mi |> Amelia::missmap(main = "Missing values vs observed")

summary(mi$readmission)
# the categorical outcome is slightly imbalanced
```

# Data Partitioning 

```{r partition, message=FALSE, warning=FALSE}
set.seed(123)
training.data = mi$readmission |> createDataPartition(p=0.7, list=F)
train.data = mi[training.data, ]
test.data = mi[-training.data, ]
```

# Model training

```{r model_training, message=FALSE, warning=FALSE}

```

